# Project information
site_name: Local PTHA documentation
site_url: https://manuelavolpe.github.io/local-PTHA-docs/
# site_author: 
site_description: >-
  Instructions and documentation for the local-PTHA workflow
 
# Repository
repo_name: manuelavolpe/local-PTHA-docs
repo_url: https://github.com/manuelavolpe/local-PTHA-docs
theme: 
  #name: material
  name: readthedocs
  logo: images/logoGTM.png
  favicon: images/logoGTM.png
  user_color_mode_toggle: true
  palette:
      primary: blue
      accent: deep orange
  #custom_dir: overrides
  features:
    - search.suggest    # display the likeliest completion for the last word
    - search.highlight  # highlight all occurrences
    - search.share      # show a share button
    - navigation.footer
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
    - announce.dismiss
    - header.autohide
plugins:
    - search
    #- awesome-pages
markdown_extensions:
  - footnotes
  - admonition
  #- mdx_math
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true 
  - attr_list
  - def_list
  - md_in_html
  - tables
    #  - pymdownx.emoji:
    #      emoji_index: !!python/name:materialx.emoji.twemoji 
    #      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css
